import Sidebar from "../component/homeComponents/Sidebar";
export const metadata = {
  title: "Auth Pages",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div className="flex max-h-screen w-full">
        <Sidebar />
        <div className="flex-1 pl-[280px] pt-10"> {/* Adjust left padding for content */}
          {children}
        </div>
      </div>
    </>
  );
}
