
import AuthNav from "../component/authNav/AuthNav";

export const metadata = {
  title: "Auth Pages",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <AuthNav></AuthNav>
      {children}
      </>
  );
}
